---
git:
  branch: master
triggers:
  cron: "@daily"
clean_workspace: true
script:
  - echo "Build SUNET Custom ARGUS Image"
  - cp docker/* .
builders:
  - docker
docker_name: sunet/argus-api
docker_tags:
  - "v1.10.2_sunetbuild"
