---
git:
  branch: master
triggers:
  cron: "@daily"
clean_workspace: true
script:
  - echo "Build SUNET Custom ARGUS Image"
builders:
  - docker
docker_context_file: docker/Dockerfile
docker_file: docker/Dockerfile
docker_context_filename: docker/Dockerfile
docker_filename: docker/Dockerfile
docker_name: sunet/argus-api
docker_tags:
  - "v1.10.2_sunetbuild"
